### ISSUE TITLE
Error: Cannot subscribe to 'page' store on the server outside of a Svelte component

### ISSUE THREAD

**Issue by deansallinen** [greymass/2nicove#151]
Error: Cannot subscribe to 'page' store on the server outside of a Svelte component, as it is bound to the current request via component context. This prevents state from leaking between users. For more information, see https://kit.svelte.dev/docs/state-management#avoid-shared-state-on-the-server
at get_store (/var/home/dean/code/greymass/unicove2/node_modules/@sveltejs/kit/src/runtime/app/stores.js:89:9)
    at Object.subscribe (/var/home/dean/code/greymass/unicove2/node_modules/@sveltejs/kit/src/runtime/app/stores.js:35:37)
    at Module.subscribe_to_store (/var/home/dean/code/greymass/unicove2/node_modules/svelte/src/store/utils.js:23:22)
    at Module.store_get (/var/home/dean/code/greymass/unicove2/node_modules/svelte/src/internal/server/index.js:320:16)
    at Array._layout (/var/home/dean/code/greymass/unicove2/src/routes/+layout.svelte:60:19)
    at Root (/var/home/dean/code/greymass/unicove2/.svelte-kit/generated/root.svelte:63:20)
    at Module.render (/var/home/dean/code/greymass/unicove2/node_modules/svelte/src/internal/server/index.js:109:2)
    at Function._render [as render] (/var/home/dean/code/greymass/unicove2/node_modules/svelte/src/legacy/legacy-server.js:32:40)
    at Module.render_response (/var/home/dean/code/greymass/unicove2/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:127:33)
    at async Module.render_page (/var/home/dean/code/greymass/unicove2/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:296:10)

**Comment by deansallinen** [comment]
Deleting the `.svelte-kit` directory and restarting the dev server seems to resolve this issue.
